const ticketModel = require('../models/ticketModel');
const memberModel = require('../models/memberModel');
const bookingModel = require('../models/bookingModel');
const { AppError } = require('../middleware/errorHandler');

const ticketService = {
  /**
   * Generate one ticket per family member for a booking.
   * qr_code = ticket UUID (generated by DB).
   */
  async generateTickets(bookingId) {
    const booking = await bookingModel.findById(bookingId);
    if (!booking) throw new AppError('Booking not found', 404);

    const members = await memberModel.findByBookingId(bookingId);
    if (members.length === 0) {
      throw new AppError('No family members found for this booking', 404);
    }

    const tickets = [];
    for (const member of members) {
      const ticket = await ticketModel.create(
        member.id,
        bookingId,
        booking.event_id,
        'placeholder'
      );
      const { pool } = require('../config/db');
      await pool.query(
        'UPDATE member_tickets SET qr_code = $1 WHERE id = $2',
        [ticket.id, ticket.id]
      );
      ticket.qr_code = ticket.id;
      tickets.push(ticket);
    }

    return tickets;
  },

  async getTicketsByBookingId(bookingId) {
    const tickets = await ticketModel.findByBookingId(bookingId);
    if (tickets.length === 0) {
      throw new AppError('No tickets found for this booking', 404);
    }
    return tickets;
  },
};

module.exports = ticketService;
